Update `theme-rebuild`
Re-ordering things so the JSON is processed before anything else.

Not sure why this is necessary, but the script was just hanging (for
more than two minutes) and this change fixed it.

diff --git a/theme-rebuild b/theme-rebuild
--- a/theme-rebuild
+++ b/theme-rebuild
@@ -1,8 +1,8 @@
 #!/bin/bash
 #
 # theme-rebuild
-# John Simpson <jms1@jms1.net> 2026-03-12
-LAST_UPDATED='2026-04-02'
+# John Simpson <jms1@jms1.net> 2026-03-12 thu
+LAST_UPDATED='2026-07-24 Fri'
 #
 # Rebuild the theme files in the theme-template/ directory.
 # - Run 'mdbook-fix-templates', which builds new *.hbs and
@@ -10,10 +10,42 @@ LAST_UPDATED='2026-04-02'
 # - Copy all css/*.css files to theme/css/
 #
 # NOTE: it's important that nothing in this script sends anything to STDOUT,
-# other than the `jq` command at the end. This is why every other command in
-# the script has `1>&2`, to send any possible output to STDERR.
+# other than the `jq` command. This is why every other command in the script
+# has `1>&2`, to send any possible output to STDERR.
 
-########################################
+###############################################################################
+###############################################################################
+###############################################################################
+#
+# Make sure the tools we need are available. If not, you should either install
+# them, or updae the PATH= line above and make sure the directories where the
+# tools are installed, are present in the PATH.
+
+TOOLS=( jq )
+
+FAIL=false
+for X in "${TOOLS[@]}"
+do
+    if ! type -t "$X" > /dev/null
+    then
+        echo "ERROR: '$X' is not available in your PATH, cannot continue"
+        FAIL=true
+    fi
+done
+
+if $FAIL
+then
+    exit 1
+fi
+
+###############################################################################
+#
+# Print the second element from the JSON structure, without any modifications.
+
+jq -r -M '.[1]'
+
+###############################################################################
+#
 # Maybe rebuild the `*.hbs` and `css/variables.css` files
 # in the theme-template/ directory.
 
@@ -24,8 +56,3 @@ LAST_UPDATED='2026-04-02'
 
 mkdir -p theme/css 1>&2
 cp theme-template/css/*.css theme/css/ 1>&2
-
-########################################
-# Give mdbook a copy of the input, without any changes
-
-jq -r -M '.[1]'
